"""Fine-tuned CRNN OCR engine wrapper for Sentinel CCTV.

This module loads the `models/plate_ocr_ft.pt` weights generated by
`scripts/train_plate_recognizer.py` and provides a clean interface
for the `PlateOCR` consensus pipeline.
"""
import logging
from pathlib import Path
from typing import Optional, Tuple

import cv2
import numpy as np
import torch
import torch.nn as nn

log = logging.getLogger("plate_recognizer_ft")
ROOT = Path(__file__).resolve().parent.parent.parent

CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
NUM_CLASSES = len(CHARS) + 1
IMG_H = 32
IMG_W = 128

def preprocess(img: np.ndarray) -> np.ndarray:
    if img.ndim == 3:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    h, w = img.shape[:2]
    scale = IMG_H / h
    new_w = int(w * scale)
    img = cv2.resize(img, (new_w, IMG_H), interpolation=cv2.INTER_CUBIC)
    if new_w > IMG_W:
        start = (new_w - IMG_W) // 2
        img = img[:, start:start + IMG_W]
    elif new_w < IMG_W:
        pad = np.full((IMG_H, IMG_W - new_w), int(img.mean()), dtype=np.uint8)
        img = np.concatenate([img, pad], axis=1)
    return img.astype(np.float32) / 255.0

def decode_greedy(logits: torch.Tensor) -> Tuple[str, float]:
    probs = torch.softmax(logits, dim=-1)
    max_probs, preds = torch.max(probs, dim=-1)
    
    pred = preds.cpu().numpy()[0]
    prob = max_probs.cpu().numpy()[0]
    
    out = []
    confs = []
    prev = -1
    for p, c in zip(pred, prob):
        if p != prev and p != 0:
            out.append(CHARS[p - 1])
            confs.append(c)
        prev = p
        
    text = "".join(out)
    conf = float(np.mean(confs)) if confs else 0.0
    return text, conf

class CRNN(nn.Module):
    """Small CRNN: MobileNetV3-S features → BiLSTM × 2 → linear."""
    def __init__(self, num_classes: int = NUM_CLASSES):
        super().__init__()
        import torchvision.models as tv
        backbone = tv.mobilenet_v3_small(weights=None)
        backbone.features[0][0] = nn.Conv2d(
            1, 16, kernel_size=3, stride=(2, 1), padding=1, bias=False,
        )
        self.features = backbone.features
        self.pool = nn.AdaptiveAvgPool2d((1, None))
        self.rnn = nn.LSTM(
            input_size=576, hidden_size=256,
            num_layers=2, bidirectional=True, batch_first=True, dropout=0.1,
        )
        self.classifier = nn.Linear(512, num_classes)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        f = self.features(x)
        f = self.pool(f)
        f = f.squeeze(2).permute(0, 2, 1)
        out, _ = self.rnn(f)
        logits = self.classifier(out)
        return logits

class FineTunedOCR:
    def __init__(self):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model_path = ROOT / "models" / "plate_ocr_ft.pt"
        if not self.model_path.exists():
            raise FileNotFoundError(f"Model not found: {self.model_path}")
            
        self.model = CRNN().to(self.device)
        ckpt = torch.load(self.model_path, map_location=self.device, weights_only=False)
        if isinstance(ckpt, dict) and "state_dict" in ckpt:
            self.model.load_state_dict(ckpt["state_dict"])
        else:
            self.model.load_state_dict(ckpt)
        self.model.eval()
        log.info("Loaded fine-tuned CRNN onto %s", self.device)

    def read(self, img: np.ndarray) -> Optional[Tuple[str, float]]:
        if img is None or img.size == 0:
            return None
            
        try:
            x = preprocess(img)
            x_tensor = torch.from_numpy(x).unsqueeze(0).unsqueeze(0).to(self.device)
            with torch.no_grad():
                logits = self.model(x_tensor)
            
            text, conf = decode_greedy(logits)
            if not text:
                return None
            return text, conf
        except Exception as e:
            log.warning("FineTunedOCR inference failed: %s", e)
            return None
